
language: node_js

node_js:
  - "node"

env:
  - NODE_ENV=test

script: npm run test

before_script:
 - npm install
 - npm run db-migrate && npm run db-seed-all
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run db-undo-migrate

after_success: npm run coverage
